---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Create a firewall policy
      oneandone_firewall_policy:
        name: ansible-firewall-policy
        description: Testing creation of firewall policies with ansible
        rules:
         -
           protocol: TCP
           port_from: 80
           port_to: 80
           source: 0.0.0.0
        wait: true
        wait_timeout: 500
