---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Delete a firewall policy
      oneandone_firewall_policy:
        name: ansible-firewall-policy
        wait: true
        wait_timeout: 500
        state: absent
