---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Remove a rule from a firewall policy
      oneandone_firewall_policy:
        firewall_policy: ansible-firewall-policy-updated
        description: Removing a rule from a firewall policy
        remove_rules:
         - rule_id
        wait: true
        wait_timeout: 500
        state: update

