---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Remove server from a firewall policy
      oneandone_firewall_policy:
        firewall_policy: ansible-firewall-policy-updated
        remove_server_ips:
         - server_ip_id
        wait: true
        wait_timeout: 500
        state: update
