---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Delete a load balancer
      oneandone_load_balancer:
        name: ansible load balancer
        wait: true
        wait_timeout: 500
        state: absent
