---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Update a load balancer
      oneandone_load_balancer:
        load_balancer: ansible load balancer updated
        description: Adding server to a load balancer with ansible
        add_server_ips:
         - server_id
        wait: true
        wait_timeout: 500
        state: update
