---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Update a load balancer
      oneandone_load_balancer:
        load_balancer: ansible load balancer
        name: ansible load balancer updated
        description: Testing the update of a load balancer with ansible
        wait: true
        wait_timeout: 500
        state: update
