---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Update a load balancer add rules
      oneandone_load_balancer:
        load_balancer: ansible load balancer updated
        description: Adding rules to a load balancer with ansible
        add_rules:
         -
           protocol: TCP
           port_balancer: 70
           port_server: 70
           source: 0.0.0.0
         -
           protocol: TCP
           port_balancer: 60
           port_server: 60
           source: 0.0.0.0
        wait: true
        wait_timeout: 500
        state: update
