---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Update a load balancer remove rule
      oneandone_load_balancer:
        load_balancer: ansible load balancer updated
        description: Removing rules from a load balancer with ansible
        remove_rules:
         - rule_id
        wait: true
        wait_timeout: 500
        state: update
