---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Detach a server from a monitoring policy
      oneandone_monitoring_policy:
        monitoring_policy: ansible monitoring policy updated
        remove_servers:
         - server_id
        wait: true
        state: update
