---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Update a monitoring policy
      oneandone_monitoring_policy:
        monitoring_policy: ansible monitoring policy
        name: ansible monitoring policy updated
        description: Testing monitoring policy update with ansible
        email: other@emailaddress.com
        thresholds:
         - 
           cpu:
             warning:
               value: 70
               alert: false
             critical:
               value: 90
               alert: false
         - 
           ram:
             warning:
               value: 70
               alert: false
             critical:
               value: 80
               alert: false
         - 
           disk:
             warning:
               value: 70
               alert: false
             critical:
               value: 80
               alert: false
         - 
           internal_ping:
             warning:
               value: 60
               alert: false
             critical:
               value: 90
               alert: false
         - 
           transfer:
             warning:
               value: 900
               alert: false
             critical:
               value: 1900
               alert: false
        wait: true
        state: update
