---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:

    - name: Remove members
      oneandone_private_network:
        private_network: ansible_private_network
        remove_members:
         - server_id
        state: update
