---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Delete a public IP
      oneandone_public_ip:
        public_ip_id: public ip id
        state: absent
        wait: true
        wait_timeout: 500
