---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Create a public IP
      oneandone_public_ip:
        datacenter: US
        reverse_dns: secondtest.com
        wait: true
        wait_timeout: 500
