---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Update a public IP
      oneandone_public_ip:
        public_ip_id: public ip id
        reverse_dns: thirdtest.com
        state: update
        wait: true
        wait_timeout: 500
