---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Create a role
      oneandone_roles:
        name: ansible_test_role
        wait: true
        wait_timeout: 500
