---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Update a user
      oneandone_user:
        user: user id
        description: Updated a user with ansible
        state: update
        wait: false
