---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Delete a user
      oneandone_users:
        name: user id (or name)
        state: absent
        wait: true
        wait_timeout: 500
