---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Create a user
      oneandone_user:
        name: ansible_user
        description: Create a user with ansible
        password: Ansib1e_pa$$word
        email: user@example.com
        wait: true
        wait_timeout: 500
