---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Update a VPN
      oneandone_vpn:
        vpn: ansible VPN
        name: ansible VPN updated
        description: Create a VPN using ansible - updated
        wait: true
        wait_timeout: 500
        state: update
