---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Create a VPN
      oneandone_vpn:
        datacenter: US
        name: ansible VPN
        description: Create a VPN using ansible
        wait: true
        wait_timeout: 500
