---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Delete a VPN
      oneandone_vpn:
        vpn: ansible VPN updated
        wait: true
        wait_timeout: 500
        state: absent
